routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('albums', 'AlbumController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Album;
use Illuminate\Http\Request;

class AlbumController extends Controller
{
    public function __construct()
    {
        $this->middleware("auth");
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums = Album::all();
        return view('albums.index',compact('albums',$albums));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('albums.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $allData = $request->all();
            if($request->hasFile('picture')){
                $fileName = time().'-'.$request->picture->getClientOriginalName();
                $request->picture->move(public_path('pictures/albums'), $fileName);
                $allData['picture'] = $fileName;
            }else{
                $allData['picture'] = null;
            }
            Album::create($allData);
            return redirect()->route('albums.index')->with('message', 'Data has been inserted successfully');
        }catch(QueryException $e){
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function show(Album $album)
    {
        return view('albums.show',compact('album',$album));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function edit(Album $album)
    {
        return view('albums.edit',compact('album',$album));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Album $album)
    {
        try{
            $allData = $request->all();
            $oldImage = $album->picture;
            if($request->picture){
                $fileName= time().'_'.$request->picture->getClientOriginalName();
                $request->picture->move(public_path('/pictures/albums/'), $fileName);
                $allData['picture'] = $fileName;
                if(file_exists(public_path("/pictures/albums/$oldImage"))){
                    unlink(public_path("/pictures/albums/$oldImage"));
                }
            }
            else{
                $allData['picture']= $oldImage;
            }
            $album->update($allData);
            return redirect()->route('albums.index')->with('message', "Data has been updated successfully");
        }catch(QueryException $e){
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function destroy(Album $album)
    {
        try{

            $oldImage = $album->picture;
            if(file_exists(public_path("/pictures/albums/$oldImage"))){
                unlink(public_path("/pictures/albums/$oldImage"));
            }

            $album->delete($oldImage);

            return redirect()->route('albums.index')->with('message', 'Data has been deleted successfully');
        }catch(QueryException $e){
            return redirect()->route('albums.index')->withErrors($e->getMessage());
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/albums/create.blade.php
@extends('layout.mainlayout')

@section('content')
    <div class="container mb-4">
        <h4>Create Album</h4>
        <hr>

        {!! Form::open(array('url' => 'albums','method' => 'POST', 'enctype'=>'multipart/form-data')) !!}

        <div class="form-group row">
            {{Form::label('title', 'Picture Title', ['class'=>'col-sm-3 col-form-label'])}}
            <div class="col-sm-9">
                {{Form::text('title', old('title') ? old('title') : (!empty($product) ? $product->title : null),['class'=>'form-control','placeholder' => 'Enter Title Here'])}}
            </div>
        </div>

        <div class="form-group row">
            {{Form::label('picture', "Picture", ['class'=>'col-sm-3 col-form-label'])}}
            <div class="col-sm-9">

                {{Form::file("picture",['class'=>'form-control-file', 'accept'=>'image/*'])}}
            </div>
        </div>

        <div class="form-group row">
            {{Form::label('description', 'Description', ['class'=>'col-sm-3 col-form-label'])}}
            <div class="col-sm-9">
                {{Form::text('description',old('description') ? old('description') : (!empty($product) ? $product->description : null),['class'=>'form-control','placeholder'=>'Type here...'])}}
            </div>
        </div>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            {{--<button type="submit" class="btn btn-primary">Submit</button>--}}

        {{Form::submit('Submit', ['class'=>'btn btn-primary mr-2'])}}

        <a href="{{route('albums.index')}}" class="btn btn-light"> Cancel </a>

        {!! Form::close() !!}

    </div>

@endsection

resources/views/albums/edit.blade.php
@extends('layout.mainlayout')

@section('content')

    <div class="col-10 offset-1 grid-margin stretch-card mb-2">

        <div class="card">
            <div class="card-header">
                <h4 class="card-title text-center"> Edit Album</h4>

                @if($errors->any())
                    @foreach($errors->all() as $error)
                        <div class="alert alert-danger"> {{$error}} </div>
                    @endforeach
                @endif
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                {!! Form::open(array('url' => 'albums/'.$album->id,'method' => 'put', 'enctype'=>'multipart/form-data')) !!}


                <div class="form-group row">
                    {{Form::label('title', 'Title', ['class'=>'col-sm-3 col-form-label'])}}
                    <div class="col-sm-9">
                        {{Form::text('title', old('title') ? old('title') : (!empty($album) ? $album->title : null),['class'=>'form-control','placeholder' => 'Enter Title Here'])}}
                    </div>
                </div>
                <div class="form-group row">
                    {{Form::label("picture", "Picture", ['class'=>'col-sm-3 col-form-label'])}}
                    <div class="col-sm-9">
                        {{Form::file("picture",['class' => 'form-control-file','accept'=>'image/*'])}}
                        <img width="100px" height="80px" src="{{asset("/pictures/albums/".$album->picture)}}" alt="Not Found">
                    </div>
                </div>

                <div class="form-group row">
                    {{Form::label('description', 'Description', ['class'=>'col-sm-3 col-form-label'])}}
                    <div class="col-sm-9">
                        {{Form::text('description',old('description') ? old('description') : (!empty($album) ? $album->description : null),['class'=>'form-control','placeholder'=>'Type here...'])}}
                    </div>
                </div>


                {{Form::submit('Update', ['class'=>'btn btn-primary mr-2'])}}

                <a href="{{route('albums.index')}}" class="btn btn-light"> Cancel </a>

                {!! Form::close() !!}

            </div> <!-- card-body -->
        </div> <!-- end card -->
    </div>


@endsection

resources/views/albums/index.blade.php
@extends('layout.mainlayout')

@section('content')
    @if (Session::has('message'))
        <div class="alert alert-info">{{ Session::get('message') }}</div>
    @endif

    <div class="container mb-2">

        <a class="btn btn-secondary easyAccess mt-1 mb-1" href="{{route('albums.create')}}">Add New Photo </a>
        <a class="btn btn-secondary easyAccess float-right mt-1 mb-1" href="{{route('home')}}">Back to Dashboard </a>
        <table class="table">
            <thead class="thead-dark">
<h5 class="text-center">The CRUD Album</h5>
            <tr>
                <th scope="col">Sl.</th>
                <th scope="col">Title</th>
                <th scope="col">Picture</th>
                <th scope="col">Description</th>
                <th scope="col">Created At</th>
                <th scope="col">Modified At</th>
                <th scope="col" class="text-center">Action</th>
            </tr>
            </thead>
            <tbody>
            @php $sl=1 @endphp
            @foreach($albums as $album)
                <tr>
                    <td>{{$sl++}}</td>

                    <td> {{$album->title}} </td>
                    <td>
                        @if(!empty($album->picture))
                            <img width="100px" height="80px" src="{{asset("/pictures/albums/".$album->picture)}}" alt="Not Found"> </td>
                    @else
                        <strong> {{"Empty Image"}} </strong>
                    @endif

                    <td>{{$album->description}}</td>

                    <td>{{$album->created_at->toFormattedDateString()}}</td>

                    <td>{{$album->updated_at->toFormattedDateString()}}</td>

                    <td>
                        <div class="btn-group" role="group" aria-label="Basic example">

                            <a href="{{ URL::to('albums/' . $album->id . '/edit') }}">
                                <button type="button" class="btn btn-warning mr-1">Edit</button>
                            </a>

                            <a href="{{route('albums.show', $album->id)}}">
                                <button type="button" class="btn btn-success mr-1">Show</button>
                            </a>

                            {!! Form::open(array('url' => route('albums.destroy', $album->id),'method' => 'delete', 'class' => 'deleteForm pull-left')) !!}
                            {{ Form::button('Delete', ['type' => 'submit', 'class' => 'btn btn-danger'])}}
                            {!! Form::close() !!}

                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

    </div>

@endsection

resources/views/albums/show.blade.php
@extends('layout.mainlayout')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center"> Show Picture Details</h4>

                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <tbody>
                            <tr class="bg-light">
                                <td> <strong> Field Name </strong></td>
                                <td> <strong> Details </strong></td>
                            </tr>


                            <tr>
                                <td> Title </td>
                                <td> {{$album->title}} </td>
                            </tr>
                            <tr>
                                <td> Picture </td>
                                <td><img width="200px" height="150px" src="{{asset('/pictures/albums/'.$album->picture)}}" alt=""> </td>
                            </tr>

                            <tr>
                                <td> Description </td>
                                <td> {{$album->description}} </td>
                            </tr>


                            </tbody>
                        </table>
                    </div> <!-- end table-responsive -->
                    <br>
                    <a href="{{route('albums.index')}}" > &laquo; Go Back </a>
                </div> <!-- end card body -->
            </div> <!-- card -->
        </div><!-- end col-lg-12 grid-margin stretch-card -->
    </div> <!-- end row -->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!

                        <a class="btn btn-info easyAccess" style="float:right" href="{{url('albums')}}">Go to Album </a>



                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout/mainlayout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('layout.partials.head')
</head>

<body>

@include('layout.partials.nav')

@yield('content')

@include('layout.partials.footer')

@include('layout.partials.footer-scripts')


</body>
</html>

resources/views/layout/partials/footer-scripts.blade.php
<!-- Bootstrap core JavaScript
================================================= -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

resources/views/layout/partials/footer.blade.php
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap!</p>

    </div>
</footer>

resources/views/layout/partials/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>Album example for ChangeTechBD</title>

<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">


<!-- Custom styles for this template -->
{{--
<link href="/css/album.css" rel="stylesheet">--}}

resources/views/layout/partials/header.blade.php
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
            <a href="#" class="btn btn-primary">Main call to action</a>
            <a href="#" class="btn btn-secondary">Secondary action</a>
        </p>
    </div>
</section>

resources/views/layout/partials/nav.blade.php
<div class="collapse bg-inverse" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 mt-2">
                <h4 class="text-white">About ChangeTech</h4>
                <p class="text-muted">Most Leading IT Company in the country, based on Chattogram.</p>
            </div>
            <div class="col-sm-4 mt-2">
                <h4 class="text-white">Contact</h4>
                <ul class="list-unstyled">

                    <li><a href="#" class="text-white">Like on Facebook</a> | <a href="#" class="text-white">Email Us</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
    <div class="container d-flex justify-content-between">
        <a href="#" class="navbar-brand">ChangeTech <img src="/pictures/icon.png" style="width:40px; height: 40px;" alt="pic"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>